// @koala-prepend "libs/jquery/3.4.1/jquery-3.4.1.js"
// @koala-prepend "libs/jsrender/1.0.4/jsrender.js"
// @koala-prepend "src/classes/Template.js"
// @koala-prepend "src/classes/render/AbstractRender.js"
// @koala-prepend "src/classes/render/RenderExternalTemplate.js"
// @koala-prepend "src/classes/render/RenderLocalTemplate.js"
